### ISSUE TITLE
Transition from XmlSecTool to xmlsec

### ISSUE THREAD

**Issue by sanmai-NL** [clarin-eric/pyFF_config#1]
[`XmlSecTool`](https://wiki.shibboleth.net/confluence/display/SHIB2/XmlSecTool) is a big dependency, that depends on a Java runtime. Furthermore it is presented by Shibboleth as being 'not supported for production use'.
In order to keep virtualized distributions of this project of reasonable size, while still using simple command line utilities instead of custom code, migrate to
[`xmlsec`](https://www.aleksey.com/xmlsec/index.html).

**Comment by sanmai-NL** [comment]
Blocked by https://bugs.alpinelinux.org/issues/4554.

**Comment by andmor-** [comment]
This is solved by our [1.5.0 release](https://gitlab.com/CLARIN-ERIC/docker-spf-md-pipelines/-/releases) of the SPF pipelines Docker image (our  virtualized distribution).
